# Site settings
title: KAZUMITS
email: kazumits@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    きまぐれに更新します
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kazumits.github.io" # the base hostname & protocol for your site
twitter_username: tnkysr
github_username: kazumits 

# Build settings
markdown: kramdown
kramdown:
  input: GFM
# markdown: redcarpet
# redcarpet:
  # extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
